package io.jimble.db.internal.generator;

import io.jimble.db.DB;
import io.jimble.util.data.Data;
import io.jimble.util.string.StringUtil;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * PostgreSQL のテーブル定義を読む（要件 F-D-30 / D-98）
 *
 * <p>
 * MySQL の {@code SHOW ...} にあたるものが無いので {@code pg_catalog} を引く。
 * {@code information_schema} を使わないのは、<b>型名がそこでは
 * {@code character varying} の「長さ抜き」になる</b>など、
 * 欲しい形で取れないものがあるためである（{@code format_type} なら
 * {@code character varying(50)} が返る）。
 * </p>
 *
 * <h2>MySQL と揃わないところ</h2>
 * <ul>
 *   <li><b>連番。</b>PostgreSQL の {@code bigserial} は
 *       「{@code bigint} ＋ {@code nextval(...)} の既定値」でしかない。
 *       そのまま出すと<b>既定値が {@code nextval('x_id_seq')} の bigint 列</b>に見えるので、
 *       型を {@code bigserial} に戻して既定値を落とす</li>
 *   <li><b>既定値の書き方。</b>{@code 'abc'::character varying} のように型が付く。
 *       MySQL は {@code abc} なので、キャストと引用符を落として揃える</li>
 *   <li><b>部分インデックス（{@code WHERE} 付き）は一意キーとして扱わない。</b>
 *       条件に合う行の中でしか一意でないので、
 *       SQL 結果キャッシュが「どの行か」を決める根拠にはできない（要件 F-D-28）</li>
 * </ul>
 */
final class PostgreSqlTableMetaReader implements TableMetaReader {

	@Override
	public List<Data> tables (DB db) {

		List<Data> res = new ArrayList<>();

		List<Data> rows = db.selectList("""
			SELECT
				c.relname                                        AS name
				, COALESCE(obj_description(c.oid, 'pg_class'), '') AS comment
			FROM pg_class c
			JOIN pg_namespace n ON n.oid = c.relnamespace
			WHERE
				n.nspname = current_schema()
				AND c.relkind IN ('r', 'p', 'v', 'm')
				AND NOT c.relispartition
			ORDER BY c.relname
			""");

		required(db, rows, "テーブル一覧");

		for (Data row : rows) {
			res.add(new Data()
				.putData("name", row.getString("name"))
				.putData("comment", row.getStringOptional("comment")));
		}

		return res;

	}

	@Override
	public List<Data> columns (DB db, String table) {

		List<Data> res = new ArrayList<>();

		List<Data> rows = db.selectList("""
			SELECT
				a.attname                                  AS name
				, format_type(a.atttypid, a.atttypmod)     AS type
				, NOT a.attnotnull                         AS nullable
				, COALESCE(col_description(a.attrelid, a.attnum), '') AS comment
				, pg_get_expr(d.adbin, d.adrelid)          AS default_value
				, a.attidentity                            AS identity
				, EXISTS (
					SELECT 1 FROM pg_index i
					WHERE i.indrelid = a.attrelid AND i.indisprimary AND a.attnum = ANY(i.indkey)
				)                                          AS primary_key
			FROM pg_attribute a
			JOIN pg_class c ON c.oid = a.attrelid
			JOIN pg_namespace n ON n.oid = c.relnamespace
			LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
			WHERE
				n.nspname = current_schema()
				AND c.relname = ?
				AND a.attnum > 0
				AND NOT a.attisdropped
			ORDER BY a.attnum
			""", table);

		required(db, rows, "列一覧: " + table);

		for (Data row : rows) {

			String type = row.getString("type");
			String defaultValue = row.getString("default_value");
			String extra = "";

			/*
			 * 連番は「型 ＋ nextval の既定値」でできている。
			 * ばらしたまま出すと、生成される DDL が<b>連番でない列</b>になる。
			 */
			if (defaultValue != null && defaultValue.startsWith("nextval(") && isSerial(type)) {
				type = serialType(type);
				defaultValue = null;
			} else if (row.getString("identity") != null && !row.getString("identity").isEmpty()) {
				// a = GENERATED ALWAYS / d = GENERATED BY DEFAULT
				extra = "a".equals(row.getString("identity"))
					? "generated always as identity"
					: "generated by default as identity";
			}

			res.add(new Data()
				.putData("name", row.getString("name"))
				.putData("type", type)
				.putData("extra", extra)
				.putData("nullable", row.getBoolean("nullable"))
				.putData("primary_key", row.getBoolean("primary_key"))
				.putData("comment", row.getStringOptional("comment"))
				.putData("default_value", literal(defaultValue)));

		}

		return res;

	}

	@Override
	public List<Data> indexes (DB db, String table) {

		List<Data> res = new ArrayList<>();

		List<Data> rows = db.selectList("""
			SELECT
				ci.relname             AS name
				, a.attname            AS column_name
				, k.ord                AS seq
				, i.indisprimary       AS is_primary
				, (i.indisunique AND i.indpred IS NULL) AS is_unique
				, (i.indexprs IS NOT NULL)              AS has_expression
				, pg_get_expr(i.indpred, i.indrelid)    AS predicate
			FROM pg_index i
			JOIN pg_class c   ON c.oid = i.indrelid
			JOIN pg_class ci  ON ci.oid = i.indexrelid
			JOIN pg_namespace n ON n.oid = c.relnamespace
			JOIN LATERAL unnest(i.indkey) WITH ORDINALITY AS k(attnum, ord) ON true
			LEFT JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = k.attnum
			WHERE
				n.nspname = current_schema()
				AND c.relname = ?
				AND i.indisvalid
				AND k.ord <= i.indnkeyatts
			ORDER BY ci.relname, k.ord
			""", table);

		required(db, rows, "インデックス一覧: " + table);

		/*
		 * 式（{@code lower(code)} など）を含むインデックスは<b>丸ごと捨てる</b>。
		 *
		 * 式の列は {@code indkey} に 0 が入り、{@code pg_attribute} に行が無い。
		 * 落ちた列を黙って無視すると、<b>実際には一意でない列の組を
		 * 一意キーとして宣言する</b>ことになる（要件 F-D-28 が
		 * 「どの行か」を決める根拠を誤る）。
		 */
		Set<String> hasExpression = new HashSet<>();

		for (Data row : rows) {
			if (row.getBoolean("has_expression") || row.getString("column_name") == null) {
				hasExpression.add(row.getString("name"));
			}
		}

		for (Data row : rows) {

			if (hasExpression.contains(row.getString("name"))) {
				continue;
			}

			res.add(new Data()
				.putData("name", row.getString("name"))
				.putData("column_name", row.getString("column_name"))
				.putData("seq", row.getInt("seq"))
				.putData("is_primary", row.getBoolean("is_primary"))
				.putData("is_unique", row.getBoolean("is_unique"))
				.putData("predicate", row.getString("predicate")));

		}

		return res;

	}

	/**
	 * カタログを引けなかったら落とす
	 *
	 * <p>
	 * {@code DB#selectList} は失敗しても例外ではなく null を返す。
	 * <b>そのまま空として通すと、列も一意キーも無いクラスが生成される。</b>
	 * 生成物は「テーブルが空だった」ようにしか見えないので、いちばん気づけない。
	 * </p>
	 *
	 * @param db	DB
	 * @param rows	結果
	 * @param what	何を引いていたか
	 * @throws GeneratorException	引けなかった場合
	 */
	private static void required (DB db, List<Data> rows, String what) {

		if (rows != null) {
			return;
		}

		throw new GeneratorException("テーブル定義を引けませんでした（%s）: %s".formatted(what, db.getError()));

	}

	/**
	 * 連番にできる型か
	 *
	 * @param type	型
	 * @return	できる場合 = true
	 */
	private static boolean isSerial (String type) {

		return switch (type.toLowerCase(Locale.ROOT)) {
			case "bigint", "smallint", "integer" -> true;
			default -> false;
		};

	}

	// region 揃える

	/**
	 * 連番の型に戻す
	 *
	 * @param type	{@code format_type} の型
	 * @return	連番の型
	 */
	private static String serialType (String type) {

		return switch (type.toLowerCase(Locale.ROOT)) {
			case "bigint" -> "bigserial";
			case "smallint" -> "smallserial";
			case "integer" -> "serial";
			default -> type;
		};

	}

	/**
	 * 既定値を MySQL と同じ形にする
	 *
	 * <p>
	 * {@code 'abc'::character varying} → {@code abc}。
	 * 関数（{@code now()} など）はそのまま返す。
	 * </p>
	 *
	 * @param value	{@code pg_get_expr} の結果
	 * @return	既定値
	 */
	private static String literal (String value) {

		if (value == null) {
			return null;
		}

		String text = value.trim();

		/*
		 * ::型 のキャストを落とす。
		 *
		 * <b>「リテラル1つ ＋ 型」の形のときだけ</b>にする。
		 * {@code 'a'::text || 'b'::text} のような式で最初の :: を切ると、
		 * <b>残り半分が黙って消えて 'a' になる</b>。
		 */
		int cast = castIndex(text);
		if (cast >= 0 && isTypeName(text.substring(cast + 2))) {
			text = text.substring(0, cast).trim();
		}

		// 'abc' → abc（'' は ' に戻す）
		if (text.length() >= 2 && text.charAt(0) == '\'' && text.charAt(text.length() - 1) == '\'') {
			text = text.substring(1, text.length() - 1).replace("''", "'");
		}

		return text;

	}

	/**
	 * 型名だけか（{@code character varying(50)} / {@code text[]} など）
	 *
	 * @param text	{@code ::} のうしろ
	 * @return	型名だけなら true
	 */
	private static boolean isTypeName (String text) {

		return text.trim().matches("[A-Za-z_][A-Za-z0-9_ ]*(\\(\\d+(,\\s*\\d+)?\\))?(\\[\\])*");

	}

	/**
	 * 引用符の外にある {@code ::} の位置
	 *
	 * @param text	式
	 * @return	位置。無ければ -1
	 */
	private static int castIndex (String text) {

		boolean inQuote = false;

		for (int i = 0; i < text.length() - 1; i++) {

			char c = text.charAt(i);

			if (c == '\'') {
				inQuote = !inQuote;
				continue;
			}

			if (!inQuote && c == ':' && text.charAt(i + 1) == ':') {
				return i;
			}

		}

		return -1;

	}

	// endregion

	// region 生成する SchemaSQL の書き方

	/**
	 * {@inheritDoc}
	 *
	 * <p>PostgreSQL は列の定義にコメントを書けない。{@code COMMENT ON} を別に出す。</p>
	 */
	@Override
	public boolean inlineComment () {

		return false;

	}

	@Override
	public String tableCommentSql (String table, String comment) {

		return "comment on table %s is '%s';".formatted(table, quote(comment));

	}

	@Override
	public String columnCommentSql (String table, String column, String comment) {

		return "comment on column %s.%s is '%s';".formatted(table, column, quote(comment));

	}

	/**
	 * {@inheritDoc}
	 *
	 * <p>
	 * <b>関数と真偽値は囲まない。</b>
	 * {@code timestamp ... default 'CURRENT_TIMESTAMP'} は、
	 * PostgreSQL が文字列を日時として読もうとして落ちる。
	 * </p>
	 */
	@Override
	public String defaultValueSql (Class<?> typeClass, String value) {

		String text = value.trim();

		/*
		 * <b>列の型で決める。</b>見た目だけで決めると、
		 * varchar 列の既定値 '123' が {@code default 123} になり
		 * （PostgreSQL は integer を varchar に入れられないので落ちる）、
		 * '(未設定)' が裸で出て構文エラーになる。
		 */
		if (String.class.equals(typeClass)) {
			return "'" + quote(text) + "'";
		}

		if (text.isEmpty()) {
			return "''";
		}

		if ("true".equalsIgnoreCase(text) || "false".equalsIgnoreCase(text) || "null".equalsIgnoreCase(text)) {
			return text.toLowerCase(Locale.ROOT);
		}

		// 関数（now() など）と、CURRENT_TIMESTAMP のような予約語
		if (text.endsWith(")") || text.toUpperCase(Locale.ROOT).startsWith("CURRENT_")) {
			return text;
		}

		// 数はそのまま
		if (text.matches("[+-]?\\d+(\\.\\d+)?")) {
			return text;
		}

		return "'" + quote(text) + "'";

	}

	@Override
	public String addPrimaryKeySql (String table, List<String> columns) {

		return "alter table %s add primary key (%s);".formatted(table, StringUtil.concat(", ", columns));

	}

	/**
	 * {@inheritDoc}
	 *
	 * <p>PostgreSQL に {@code add unique index} は無い。制約として足す。</p>
	 */
	@Override
	public String addUniqueSql (String table, String name, List<String> columns) {

		return "alter table %s add constraint %s unique (%s);"
			.formatted(table, name, StringUtil.concat(", ", columns));

	}

	/**
	 * {@inheritDoc}
	 *
	 * <p>PostgreSQL に {@code alter table ... add index} は無い。</p>
	 */
	@Override
	public String addIndexSql (String table, String name, List<String> columns, String predicate) {

		String sql = "create index %s on %s (%s)".formatted(name, table, StringUtil.concat(", ", columns));

		// 部分インデックス。落とすと「全行にかかるインデックス」になる
		if (predicate != null && !predicate.isEmpty()) {
			sql += " where " + predicate;
		}

		return sql + ";";

	}

	/**
	 * SQL の文字列リテラルに入れる
	 *
	 * @param text	文字列
	 * @return	囲みの中身
	 */
	private static String quote (String text) {

		return text.replace("'", "''");

	}

	// endregion

}
